### ISSUE TITLE
Topic list not listing subscribed topics

### ISSUE THREAD

**Issue by jennuine** [gazebosim/gz-transport#263]
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
Source both in Dome and Fortress branches

## Description
* Expected behavior: `ign topic -l` to list topics that are being subscribed to
* Actual behavior: Does not list topic until it's published then disappears

## Steps to reproduce

1. `ign gazebo velocity_control.sdf` (this also happens with `diff_drive.sdf` as well)
2. Add topic viewer in gui
3. `ign topic -e -t /model/vehicle_blue/cmd_vel`
4. `ign topic -t "/model/vehicle_blue/cmd_vel" -m ignition.msgs.Twist -p "linear: {x: 0.5}, angular: {z: 0.05}"`

## Output

I came across this when I wanted to check the green vehicle's initial `cmd_vel` and wasn't able to.

![Peek 2021-09-24 12-53](https://user-images.githubusercontent.com/8602001/134733364-fa98fe8c-5d31-4dfa-b33a-f672d17eeb75.gif)

**Comment by caguero** [comment]
This is a known limitation. It hasn't been implemented yet.

**Comment by chapulina** [comment]
Closed #39 as a duplicate. Usually we'd close the newer issue, but I think that one may be a bit too old.

**Comment by azeey** [comment]
Fixed by https://github.com/gazebosim/gz-transport/pull/379
