### ISSUE TITLE
gz-transport12 ignition.msgs backward compatibility

### ISSUE THREAD

**Issue by scole02** [gazebosim/gz-transport#331]
## Desired behavior

For a couple days I had been scratching my head wondering why all features of my ignition fortress projects (Ignition-transport11) seemed to work in ignition garden (gz-transport12) except the ability to subscribe/publish to topics using the `ign topic` cli. It took me a while to realize that the namespace shift from `ignition` --> `gz` affected everything, *including* the namespace of the message type expected by topics and the topic cli. From my experience the `ign topic` cli using gz-transport12 is unable to publish to topics using messages from the old ignition namespace. 

Attempting to do so will throw an error like so

```
sam@sam<dock_rolling>_ros_rov:~/workspace$ ign topic --version
12.0.0~pre1
sam@sam<dock_rolling>_ros_rov:~/workspace$ ign topic -i -t /model/joint/thruster1_joint/ang_vel
Publishers [Address, Message Type]:
  tcp://172.17.0.1:41197, ignition.msgs.Double
sam@sam<dock_rolling>_ros_rov:~/workspace$ ign topic -t /model/joint/thruster4_joint/cmd_thrust -m ignition.msgs.Double -p 'data: 5'
Unable to create message of type[ignition.msgs.Double] with data[data: 5].
```

Allowing the newer gz topic cli to publish these messages would be much appreciated.

## Alternatives considered

Looking over some of the source code it looks like the message types are parsed using protobuf in the `ign-msgs` library. I am not too familiar with protobuf, and not sure how much effort would be required to enable backwards compatibility.

An error message indicating to the user that they are using a deprecated message type would at least give the user an idea of what is happening. I assume this issue will only become more common once garden is released and users attempt to publish topics in older projects that are compatible with garden, save for the old `ignition.msgs` message types.

## Implementation suggestion

Possibly adding/exposing the old protobuf definitions used in ignition-transport11 and ign-msgs, to whatever system handles message parsing?

**Comment by chapulina** [comment]
Thanks for catching this before we release Garden 😄 Let us know if you run into other tricky migration points.

Here's the tick-tock:

* https://github.com/gazebosim/gz-msgs/pull/281
