### ISSUE TITLE
Add Python bindings

### ISSUE THREAD

**Issue by srmainwaring** [gazebosim/gz-transport#387]
## Desired behavior

Add Python bindings to `gz-transport` (and `gz-msgs`).

## Alternatives considered

- Use `ros_gz` bridge and the Python support in ROS / ROS2.

## Implementation suggestion

Upstream the bindings for `gz-msgs` and `gz-transport` from `https://github.com/srmainwaring/gz-python`.

## Additional context

From time to time there are requests for Python bindings to control the simulation. A number of the requirements can be met by using the messaging infrastructure to control and interact with the simulation.

- https://community.gazebosim.org/t/python-bindings-for-gazebo-ignition/360
- https://github.com/gazebosim/gz-sim/issues/1905
- https://github.com/gazebosim/gz-transport/pull/386

**Comment by azeey** [comment]
Thanks for the implementation suggestion @srmainwaring. This is something we are hoping to address for Harmonic and having your implementation as a starting point will go a long way. We'd also like to address https://github.com/gazebosim/gz-msgs/issues/113, https://github.com/gazebosim/gz-msgs/issues/36, and https://github.com/gazebosim/gz-sim/issues/494 which might have implications for how we implement this.

**Comment by azeey** [comment]
This has been implemented in #411
