### ISSUE TITLE
`gz topic -p` publishes an empty message even when the input message to publish is invalid

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-transport#442]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? gz-transport3, 184c3dfbecbadc7bb91ff8293e1cc925b4130668

## Description
* Expected behavior: When the input message provided to `gz topic -p` is invalid, it should print an error and quit.
* Actual behavior: It prints an error and actually publishes an empty message.

## Steps to reproduce

1. In one terminal, run `gz topic -e --json-output -t chatter`
2. In another, run `gz toic -t chatter -m gz.msgs.Double -p "0.5"`

The first terminal should print `{}` indicating an empty message was received[

**Comment by mjcarroll** [comment]
https://github.com/gazebosim/gz-msgs/pull/384

**Comment by azeey** [comment]
Thanks @mjcarroll!
