### ISSUE TITLE
ModuleNotFoundError: No module named 'gz'

### ISSUE THREAD

**Issue by Andrii0607** [gazebosim/gz-transport#511]
I am trying to execute the "publisher.py" script, which is in the "python" directory. I have installed "libgz-transport10-dev" and "libgz-transport13-dev" using apt. But whenever I execute the script 
$ python3 publisher.py
I get 
ModuleNotFoundError: No module named 'gz'
error.
Do I have to install some additional packages?
I am using Ubuntu24.

**Comment by azeey** [comment]
Yeah, you'll need to install `python3-gz-transport13`. 

It would be great to include some installation instructions in https://gazebosim.org/api/transport/13/python.html. If you can help out with that, i.e, update https://github.com/gazebosim/gz-transport/blob/gz-transport13/tutorials/06_python_support.md, I would greatly appreciate it.

**Comment by Andrii0607** [comment]
@azeey 
Thank you! Your answer helped me a lot!
OK. I will update the document and open a pull request.

**Comment by Andrii0607** [comment]
@azeey 
It seems I don’t have a permission to create a new branch. Can you please grant me the permission?

**Comment by mjcarroll** [comment]
>It seems I don’t have a permission to create a new branch. Can you please grant me the permission?

You can fork the repo into your own namespace and make changes there before opening a pull request.
