### ISSUE TITLE
config.hh缺失

### ISSUE THREAD

**Issue by echo-machile** [gazebosim/gz-transport#542]
## Environment
* OS Version: 
* Source or binary build?
  
  

## Description
* Expected behavior: 
* Actual behavior: 

## Steps to reproduce

1.
2.
3.

## Output

![QQ_1726758282991](https://github.com/user-attachments/assets/07039ef1-2cce-41f4-94c5-ff61b7c4b50e)

**Comment by mjcarroll** [comment]
`config.hh` and `Export.hh` are generated by the buildsystem based on project variables.  You need to run cmake in order for them to be populated.

**Comment by azeey** [comment]
Closing since this doesn't appear to be a bug.
