### ISSUE TITLE
The msg_type argument in the node.subscribe method is unclear. (Python gz.transport14)

### ISSUE THREAD

**Issue by samh133** [gazebosim/gz-transport#548]
I am attempting to use the node.subscribe method to subscribe to a topic. It appears to require three arguments, msg_type, topic and callback. I have not been able to find in what way the msg_type variable should be passed. There does not appear to be any reference to msg_type in the documentation https://gazebosim.org/api/transport/14/messages.html. 
What values of msg_type can be passed?

![image](https://github.com/user-attachments/assets/03be6d3d-3a9d-4f69-aa78-c1acc0a8b3fb)
![image](https://github.com/user-attachments/assets/3c3dd136-979b-4636-b42f-973f25f8ca5e)
![image](https://github.com/user-attachments/assets/f4b6f3b7-dcbb-4ff4-aeec-f33b0e85be38)

**Comment by azeey** [comment]
The `msg_type` is the class that is generated from the gz-msgs proto. I believe it's covered in the python tutorial https://gazebosim.org/api/transport/14/python.html
